### ISSUE TITLE
"No videos found!" error

### ISSUE THREAD

**Issue by Mennaruuk** [aaronvegh/Fangirls#1]
I'm getting "No videos found!" error every time I input a YouTube URL. I tried different YouTube URLs but to no avail. I suspect it has to do with the recent youtube-dl takedown, but I'm not too sure.
![Screen Shot 2020-11-08 at 12 41 35 AM_censored](https://user-images.githubusercontent.com/52135169/98458102-421efe00-215b-11eb-9dae-6110df026197.jpg)

Also, on a related note, all the hyperlinks on the [Fangirls website](https://aaronvegh.github.io/Fangirls/) to the youtube-dl Github repo unfortunately do not work anymore. So it'd be great if they can be replaced with links to https://yt-dl.org or https://youtube-dl.org.

Thank you!

**Comment by aaronvegh** [comment]
Thanks @Mennaruuk! I've just updated those hyperlinks while updating a new version of Fangirls. On startup, FG will update its version of Youtube-DL. Check the Help menu to see what version it's running. It may take a few moments for that to complete. If you continue to see problems, reply with the URL you're trying and I'll try to replicate here.
